application: bdc-toys
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:

# Weathere
- url: /weathere\b.*
  script: apps.weathere.py.main.application


